import pandas as pd
df = pd.read_csv('area.csv', header=0, index_col=0)
print(df)
print("---------------------")
print(df[2:5])
print("---------------------")
print(df[1:10:2])
print("---------------------")
print(df[4:])
print("---------------------")
print(df[:5])
print("---------------------")
print(df['fifth':'ninth'])
print("---------------------")
print(df["city"])
print("---------------------")
print(df[["population","name"]])
print("---------------------")
print(df[2:5][["city","name"]])
print("---------------------")
print(df[:][['population', 'city']])
print("---------------------")
print(df['fifth':'ninth'] ["name"])
print("---------------------")
