import pandas as pd
df = pd.read_csv('area.csv', header=0, index_col=0)
print(df)
print("---------------------")
print(df.loc['third', 'city'])
print("---------------------")
print(df.loc[['sixth','eigth','tenth'], 'name'])
print("---------------------")
print(df.loc['fifth', ['population', 'city']])
print("---------------------")
print(df.loc['fifth':'ninth', 'city'])
print("---------------------")
print(df.loc["eleventh","name":"city"])
print("---------------------")
print(df.loc[:,["population","name"]])
print("---------------------")
print(df.loc['fifth':'ninth', "name":"city"])
print("---------------------")
#print(df.loc[5:9, "name"])
#print("---------------------")
#print(df.loc["first", 0:2])
#print("---------------------")
print(df.loc[['sixth','eigth','tenth'],["population","name"]])
