import pandas as pd
df = pd.read_csv('area.csv', header=0, index_col=0)
print(df)
print("---------------------")
print(df.iloc[2, 2])
print("---------------------")
print(df.iloc[[5,7,9], 0])
print("---------------------")
print(df.iloc[4, [1, 2]])
print("---------------------")
print(df.iloc[4:9, 2])
print("---------------------")
print(df.iloc[10,:])
print("---------------------")
print(df.iloc[:,[1,0]])
print("---------------------")
print(df.iloc[4:9, 0:3])
print("---------------------")
#print(df.iloc[4:9, "name"])
#print("---------------------")
#print(df.iloc["first", 0:2])
#print("---------------------")
