import pandas as pd
df = pd.read_csv('area.csv', header=0, index_col=0)
print(df)
print("---------------------")
home = pd.DataFrame({"name":"士林區","population":287214,"city":"台北市"}, index=["fourteen"])
df1 = df.append(home)
print(df1)
print("---------------------")
df2 = pd.concat([df,home])
print(df2)
print("---------------------")
df3 = df1.drop('fourteen')
print(df3)
print("---------------------")
df4 = df2.drop(index='fourteen')
print(df4)
print("---------------------")
