import pandas as pd
fortune1000 = pd.read_csv("Fortune1000.csv",index_col="Rank")
print(fortune1000.head())
print('-----------------------')
gb_sector = fortune1000.groupby('Sector')
print(type(gb_sector))
print('-----------------------')
print(gb_sector.size())
print('-----------------------')
print(gb_sector.count())
print('-----------------------')
print(gb_sector.Company.count())
print('-----------------------')
print(gb_sector.Employees.count())
print('-----------------------')
