import numpy as np
a =np.array([1,2,3,4])
print(a)
print("---------------")
a =np.arange(10)
print(a)
print("---------------")
a =np.arange(2,12,2)
print(a)
print("---------------")
a =np.linspace(0, 1, 5)
print(a)
print("---------------")
